name: Kuikly Module Build Template

on:
  workflow_call:
    inputs:
      module-name:
        required: true
        type: string

jobs:
  build-module:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546

      - name: build module
        run: |
          ./gradlew clean :${{ inputs.module-name }}:assemble