name: pr-check
on:
  # 以主干的push事件作为触发条件
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - img/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          echo Hello world
          ./gradlew clean :core:assemble
