name: pr-check
on:
  # 以主干的push事件作为触发条件
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - img/**

jobs:
  CI:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719

      - name: Build with Gradle
        run: |
          echo "Hello world"
          ./gradlew --stop
          ./gradlew clean :core:assemble
