name: pr request check

on:
  pull_request:
    branches: [personal/elixxli_mr_ci]

jobs:
  detect-changes:
    runs-on: macos-latest
    outputs:
      compose_changed: ${{ steps.check.outputs.compose }}
      core_changed: ${{ steps.check.outputs.core }}
      core_render_android_changed: ${{ steps.check.outputs.core_render_android }}
      core_ksp_changed: ${{ steps.check.outputs.core_ksp }}
      core_annotations_changed: ${{ steps.check.outputs.core_annotations }}
      core_kapt_changed: ${{ steps.check.outputs.core_kapt }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Detect changed modules
        id: check
        run: |
          echo "core_annotations=$(git diff --name-only HEAD^ HEAD | grep -q 'core-annotations/' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "core=$(git diff --name-only HEAD^ HEAD | grep -q 'core/' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "core_ksp=$(git diff --name-only HEAD^ HEAD | grep -q 'core-ksp/' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "core_render_android=$(git diff --name-only HEAD^ HEAD | grep -q 'core-render-android/' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "compose=$(git diff --name-only HEAD^ HEAD | grep -q 'compose/' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
          echo "core_kapt=$(git diff --name-only HEAD^ HEAD | grep -q 'core-kapt/' && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

  build-compose:
    needs: detect-changes
    if: needs.detect-changes.outputs.compose_changed == 'true'
    uses: ./.github/workflows/module_build.yml
    with:
      module-name: 'compose'

  build-core:
    needs: detect-changes
    if: needs.detect-changes.outputs.core_changed == 'true'
    uses: ./.github/templates/module_build.yml
    with:
      module-name: 'core'

  build-core-render-android:
    needs: detect-changes
    if: needs.detect-changes.outputs.core_render_android_changed == 'true'
    uses: ./.github/templates/module_build.yml
    with:
      module-name: 'core-render-android'

  build-core-ksp:
    needs: detect-changes
    if: needs.detect-changes.outputs.core_ksp_changed == 'true'
    uses: ./.github/templates/module_build.yml
    with:
      module-name: 'core-ksp'

  build-core-annotations:
    needs: detect-changes
    if: needs.detect-changes.outputs.core_annotations_changed == 'true'
    uses: ./.github/templates/module_build.yml
    with:
      module-name: 'core-annotations'

  build-core-compatible:
    needs: detect-changes
    if: needs.detect-changes.outputs.core_changed == 'true'
    uses: ./.github/workflows/module_build_compatible.yml
    with:
      module-name: 'core'